language: ruby
script: bundle exec jekyll build

deploy:
  # Deploy the draft branch to draft.cssu.ca on Heroku
  - provider: heroku
    api_key:
      secure: re+1hSGuZyAeVuK/7vimbPLiL55aj7uqFIdpp07lRjD7Y1CkpQTBZi2RkngK+iUZninK2dgS5sp6KV2mlJLhB4YNQ7v890/aRhPV97JWLQUbpqSDk0QczSKbw0pLpSBAVKMRkA/8XMcWTzbZobdlxLPfUv13zwaDUyEEjW7sMto=
    app: cssu
    strategy: api
    on:
      branch: draft
      repo: cssu/cssu.ca

#  - provider: script
#    script: ./deploy_pages.sh
#    # Prevent cleaning up the built '_site' directory
#    skip_cleanup: true
#    on:
#      branch: master
#      repo: cssu/cssu.ca
