# Site settings
title: CSSU
email: cssu@teach.cs.toronto.edu
url: https://cssu.ca
description: University of Toronto Computer Science Student Union
github_username: cssu
facebook_username: UofTCSSU
instagram_username: uoftcssu

# Ensures future-dated posts are shown
future: true

# Build settings
exclude: [
  'bin',
  'deploy_pages.sh',
  'out',
  'Gemfile',
  'Gemfile.lock',
  'Rakefile',
  'README.md',
  'Procfile',
  'vendor',  # Travis CI installs gems to vendor/bundle/
]

# Enable asset processing
assets:
  autoprefixer:
    browsers:
      - 'last 2 versions'
      - 'IE > 9'
  js_compressor:  uglifier
  css_compressor: sass

# Tag pages
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
